export const SET_IS_OPEN_POPAP = 'SET_IS_OPEN_POPAP';
export const SET_CONTENT_POPAP = 'SET_CONTENT_POPAP';
export const SET_TITLE_POPAP = 'SET_TITLE_POPAP';
export const SET_ON_SAVE_POPAP = 'SET_ON_SAVE_POPAP';
export const SET_ON_CLOSE_POPAP = 'SET_IS_OPEN_POPAP';
export const SET_SIZE_POPAP = 'SET_IS_OPEN_POPAP';